apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/PittampalliOrg/chat.git
    targetRevision: latest
    path: resources/nextjs/base
  destination:
    name: in-cluster
    namespace: nextjs
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
