# resources/nextjs/base/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: nextjs
data:
  # ── public URLs (unchanged) ──────────────────────────────────
  NEXTAUTH_URL:          "http://chat.localtest.me:31080"
  NEXT_PUBLIC_BASE_URL:  "http://chat.localtest.me:31080"
  NEXT_PUBLIC_SITE_URL:  "http://chat.localtest.me:31080"
  NEXT_PUBLIC_BASE_PATH: "http://chat.localtest.me"

  # ── single Alloy OTLP endpoint for all server‑side signals ───
  OTEL_EXPORTER_OTLP_ENDPOINT:  "http://alloy.monitoring.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL:  "http/protobuf"          # default, but explicit  :contentReference[oaicite:2]{index=2}
  OTEL_EXPORTER_OTLP_HEADERS:   ""                       # e.g. "X-Scope-OrgID=tenant‑a"

  # ── exporter selection (explicit, though "otlp" is the default) ────────────
  OTEL_TRACES_EXPORTER:   "otlp"
  OTEL_METRICS_EXPORTER:  "otlp"
  OTEL_LOGS_EXPORTER:     "otlp"

  # ── resource metadata & logging ─────────────────────────────
  OTEL_SERVICE_NAME:        "nextjs"
  OTEL_RESOURCE_ATTRIBUTES: "k8s.cluster.name=local-kind,service.namespace=nextjs"
  OTEL_LOG_LEVEL:           "debug"

  # ── Next.js / runtime plumbing ─────────────────────────────
  NEXT_RUNTIME:  "nodejs"
  NODE_ENV:      "development"
  REDIS_URL:     "redis://redis-service:6379"
  REDIS_AVAILABLE: "true"
  TRUST_PROXY:   "1"
