apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: nextjs
data:
  # ── public URLs ───────────────────────────────────────────────
  NEXTAUTH_URL:          "http://chat.localtest.me:3000"
  NEXT_PUBLIC_BASE_URL:  "http://chat.localtest.me:3000"
  NEXT_PUBLIC_SITE_URL:  "http://chat.localtest.me:3000"

  # ── telemetry (browser) ───────────────────────────────────────
  NEXT_PUBLIC_OTEL_TRACES_ENDPOINT: "/api/telemetry/traces"

  # ── telemetry (node & API routes) ─────────────────────────────
  TEMPO_ENDPOINT:         "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
  LOKI_ENDPOINT:          "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
  PROMETHEUS_ENDPOINT:    "http://prometheus-server.monitoring.svc.cluster.local/api/v1/write"

  # OTLP spec variables (picked-up automatically by the SDK)
  OTEL_EXPORTER_OTLP_PROTOCOL:          "http/protobuf"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:   "http://tempo.monitoring.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:  "http://monitoring-alloy-metrics.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:     "http://loki-gateway.monitoring.svc.cluster.local/loki"
  OTEL_SERVICE_NAME:                    "nextjs"

  # ── misc runtime plumbing ─────────────────────────────────────
  NODE_ENV:              "development"
  REDIS_URL:             "redis://redis-service:6379"
  REDIS_AVAILABLE:       "true"
  TRUST_PROXY:           "1"
