networks:
   production:
       external: true

volumes:
  postgres-data:

services:

  # frontend:
  #   build: .
  #   env_file:
  #     - ./.env.local
  #   ports:
  #     - "3000:3000"
  #   command: sleep infinity
  #   networks:
  #     - production
  #   depends_on:
  #     - db

  # frontend:
  #   image: plugin
  #   volumes:
  #     - .:/workspace
  #     # - /var/run/docker.sock:/var/run/docker.sock
  #     # - /home/vpittamp/.kube:/home/node/.kube
  #   environment:
  #   - NODE_ENV=development
  #   - DAPR_HTTP_PORT=3500
  #   - DAPR_GRPC_PORT=50002
  #   # --- choose ONE of the blocks below ---
  #   # Redis
  #   # - CONNECTION_REDIS_URL=[REDACTED_REDIS_URL]
    ports:
      - "3000:3000"
      - "50002:50002"
    networks:
      - production  
    depends_on:
      - db
      - redis

  frontend-dapr:
    image: daprio/daprd:latest
    command: ["./daprd",
     "-app-id", "frontend",
     "-app-port", "3000",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components",
     "-log-level", "debug"]
    volumes:
      - "./dapr/components:/components"
      - "./dapr/secrets:/secrets"
    depends_on:
      - frontend
      - redis
    network_mode: "service:frontend"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - production

  # rad:
  #   image: rad
  #   container_name: rad
  #   volumes:
  #     - ../rad/samples:/workspace
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /home/vpittamp/.kube/config:/home/node/.kube/config:ro
  #   environment:
  #     - NODE_ENV=development
  #   command: sleep infinity
  #   expose:
  #     - 3000
  #   networks:
  #     - production       


  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./lib/db/migrations:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - production  
    ports:
      - "5432:5432"
