# compose.yml  – switch stack with:  docker compose --profile dev|prod up -d

networks:
  kind:
    external: true

volumes:
  postgres-data:

services:
##############################################################################
#  FRONTEND – two variants, each with its own side-car                       #
##############################################################################

# ──────────── DEV ───────────────────────────────────────────────────────────
  frontend-dev:
    profiles: ["dev"]
    image: radius 
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker-host.sock
    entrypoint: /usr/local/share/docker-init.sh
    env_file:
      - ./.devcontainer/devcontainer.env
    command: sleep infinity # (or ["pnpm","dev"])
    ports: ["3000:3000", "50002:50002"]
    depends_on: [redis, db]
    networks: [kind]

  frontend-dapr-dev:
    profiles: ["dev"]
    image: daprio/daprd:latest
    network_mode: "service:frontend-dev"
    command:
      ["./daprd",
       "-app-id", "frontend",
       "-app-port", "3000",
       "-dapr-grpc-port", "50002",
       "-components-path", "/components",
       "-log-level", "debug"]
    volumes:
      - "./dapr/components:/components"
      - "./dapr/secrets:/secrets"
    depends_on: [frontend-dev, redis]

# ──────────── PROD ──────────────────────────────────────────────────────────
  frontend-prod:
    profiles: ["prod"]
    build:
      context: .
      target: runner
      args:
        NODE_ENV: ${NODE_ENV}
        DAPR_HTTP_PORT: ${DAPR_HTTP_PORT}
        DAPR_GRPC_PORT: ${DAPR_GRPC_PORT}
        CONNECTION_STATESTORE_COMPONENTNAME: ${CONNECTION_STATESTORE_COMPONENTNAME}
        CONNECTION_POSTGRESQL_HOST: ${CONNECTION_POSTGRESQL_HOST}
        CONNECTION_POSTGRESQL_PORT: ${CONNECTION_POSTGRESQL_PORT}
        CONNECTION_POSTGRESQL_USERNAME: ${CONNECTION_POSTGRESQL_USERNAME}
        CONNECTION_POSTGRESQL_PASSWORD: ${CONNECTION_POSTGRESQL_PASSWORD}
        CONNECTION_POSTGRESQL_DATABASE: ${CONNECTION_POSTGRESQL_DATABASE}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        SSL: ${SSL}
    image: vpittamp.azurecr.io/chat-frontend:0.1.8
    ports: ["3000:3000", "50002:50002"]
    depends_on: [db, redis]
    networks: [kind]

  frontend-dapr-prod:
    profiles: ["prod"]
    image: daprio/daprd:latest
    network_mode: "service:frontend-prod"
    command:
      ["./daprd",
       "-app-id", "frontend",
       "-app-port", "3000",
       "-dapr-grpc-port", "50002",
       "-components-path", "/components",
       "-log-level", "debug"]
    volumes:
      - "./dapr/components:/components"
      - "./dapr/secrets:/secrets"
    depends_on: [frontend-prod, redis]

##############################################################################
#  COMMON SERVICES (always started)                                          #
##############################################################################

  redis:
    image: redis:alpine
    ports: ["6379:6379"]
    networks: [kind]

  db:
    image: postgres:latest
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./lib/db/migrations:/docker-entrypoint-initdb.d:ro
    networks: [kind]

  dashboard:
    image: daprio/dashboard:latest
    command:
      ["./dashboard",
       "--listen-address", "0.0.0.0:8080",
       "--resources-path",  "/home/nonroot/.dapr/components",
       "--docker-compose-path", "/compose/compose.yml"]
    volumes:
      - ./compose.yml:/compose/compose.yml:ro
      - ./dapr/components:/home/nonroot/.dapr/components
    ports: ["8082:8080"]
    depends_on: [redis]                 # side-cars are profile-specific
    networks: [kind]
