apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.*
    helm:
      values: |
        singleBinary:
          replicas: 1

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            filesystem:
              directory: /var/loki
            bucketNames:           # chart expects these keys even for FS
              chunks: chunks
              ruler:  ruler
              admin:  admin
        test:            
            enabled: false

        gateway:
          enabled: true
          service:
            type: NodePort
            nodePort: 31000

        monitoring:
          selfMonitoring:
            enabled: false 
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false

        serviceMonitor:
          enabled: false
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
