apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  destination:
    name: in-cluster
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.*          # keep tracking the 5-series chart
    helm:
      values: |
        #############################################
        #  Loki single-binary deployment parameters #
        #############################################
        singleBinary:
          replicas: 1

        #############################################
        #  Loki server configuration                #
        #############################################
        loki:
          auth_enabled: false

          # basic HA/TSDB settings
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          storage:
            type: filesystem
            filesystem:
              directory: /var/loki
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin

          # keep the pattern-based ingestion helper
          pattern_ingester:
            enabled: true

          ###########################################
          #  Limits – allow structured metadata     #
          ###########################################
          limits_config:
            structured_metadata: true
            volume_enabled: true

          ###########################################
          #  Resource requests / limits             #
          ###########################################
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi

          ###########################################
          #  Persistent volume                      #
          ###########################################
          persistence:
            enabled: true
            size: 10Gi

          ###########################################
          #  Ruler                                  #
          ###########################################
          ruler:
            enable_api: true

        #############################################
        #  Helm test & monitoring bits              #
        #############################################
        test:
          enabled: false

        gateway:
          enabled: true
          service:
            type: NodePort
            nodePort: 31000

          readinessProbe:
            failureThreshold: 10

        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
          serviceMonitor:
            enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
