apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: default                     # <-- RESTORED
  destination:                         # <-- RESTORED
    name: in-cluster
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "5.*"
    helm:
      values: |
        # --- Loki deployment ---------------------------------------------
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            filesystem:
              directory: /var/loki
            bucketNames:           # chart expects these keys even for FS
              chunks: chunks
              ruler:  ruler
              admin:  admin

        gateway:
          enabled: true
          service:
            type: NodePort
            nodePort: 31000

        # --- turn OFF self-monitoring & Operator CRDs --------------------
        monitoring:
          selfMonitoring:
            enabled: false                   # <- no GrafanaAgent CRs
            grafanaAgent:
              installOperator: false         # <- skip Operator & CRDs
          lokiCanary:
            enabled: false

        serviceMonitor:
          enabled: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
