# apps/monitoring/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
  finalizers: [resources-finalizer.argocd.argoproj.io]

spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: 2.*
    helm:
      values: |
        cluster:
          name: local-kind

        # ── feature toggles ─────────────────────────────
        clusterMetrics: true
        podLogs:        true
        traces:         true

        # ── Alloy agents ───────────────────────────────
        alloy-metrics: true
        alloy-logs:
          extraArgs:
            - --server.http.listen-addr=0.0.0.0:12345   # Alloy UI
          config: |
            loki.write:
              endpoint: http://loki-gateway.monitoring.svc.cluster.local:3100/loki/api/v1/push
            exporters.otlphttp:
              endpoint: http://tempo.monitoring.svc.cluster.local:4318
        alloy-traces: true

        # ── Beyla auto-instrumentation ─────────────────
        beyla:
          enabled: true
          extraEnvs:
            - name: BEYLA_OPEN_PORT
              value: "3000,5432"
          destinations:
            - name: localProm
              type: prometheus
              url:  http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
              metrics: { enabled: true }

            - name: localLoki
              type: loki
              url:  http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
              logs: { enabled: true }

            - name: localTempo              # <--- fixed line
              type: otlp                    # legal value
              url:  http://tempo.monitoring.svc.cluster.local:4318
              traces: { enabled: true }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: ["CreateNamespace=true"]
