apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts          # chart repo
    chart: k8s-monitoring                                   # Alloy + Beyla + Loki + Tempo + Prom
    targetRevision: 2.*                                     # stick to v2 line
    helm:
      values: |
        cluster:
          name: local-kind        # label for all data

        # ─── Features you want ────────────────────────────────────────────────
        clusterMetrics:
          enabled: true           # kube-state-metrics, node-exporter, etc.

        # ─── Collectors (must match the feature) ──────────────────────────────
        alloy-metrics:
          enabled: true           # REQUIRED for clusterMetrics feature

        beyla:                    # optional eBPF HTTP tracing
          enabled: true
          extraEnvs:
            - name: BEYLA_OPEN_PORT
              value: "3000,5432"

        # ─── Storage back-ends (destinations) ────────────────────────────────
        prometheus:
          enabled: true           # spin up in-cluster Prometheus

        destinations:             # tell the chart where to ship metrics
          - name: localProm
            type: prometheus
            url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
            metrics:
              enabled: true

        grafana:                  # UI
          enabled: true
          service:
            type: NodePort
            nodePort: 30001       # you’ll browse to this



  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
