apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: 2.*
    helm:
      values: |
        #######################################################################
        # 1. Basic cluster identity
        #######################################################################
        cluster:
          name: local-kind

        #######################################################################
        # 2. Global feature switches
        #######################################################################
        clusterMetrics:
          enabled: true
        podLogs:
          enabled: true
        traces:
          enabled: true

        #######################################################################
        # 3. Outbound destinations
        #    (only prometheus | loki | otlp | pyroscope are allowed)
        #######################################################################
        destinations:
          - name: localProm
            type: prometheus
            url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
            metrics:
              enabled: true
          - name: localLoki
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
            logs:
              enabled: true
          - name: localTempo
            type: otlp
            url: http://tempo.monitoring.svc.cluster.local:4318
            traces:
              enabled: true

        #######################################################################
        # 4. Alloy collectors
        #######################################################################
        alloy-metrics:
          enabled: true

        alloy-logs:
          enabled: true
          extraArgs:
            - --server.http.listen-addr=0.0.0.0:12345

        alloy-traces:
          enabled: true

        #######################################################################
        # 5. Beyla auto-instrumentation (eBPF)
        #######################################################################
        beyla:
          enabled: true
          extraEnvs:
            - name: BEYLA_OPEN_PORT
              value: "3000,5432"
          destinations:
            - name: localProm
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
              metrics:
                enabled: true
            - name: localLoki
              type: loki
              url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
              logs:
                enabled: true
            - name: localTempo
              type: otlp
              url: http://tempo.monitoring.svc.cluster.local:4318
              traces:
                enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true