apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts          # chart repo
    chart: k8s-monitoring                                   # Alloy + Beyla + Loki + Tempo + Prom
    targetRevision: 2.*                                     # stick to v2 line
    helm:
      values: |
        cluster:
          name: local-kind
        clusterMetrics:
          enabled: true
        alloy-metrics:
          enabled: true
        beyla:
          enabled: true
          extraEnvs:
            - name: BEYLA_OPEN_PORT
              value: "3000,5432"
        prometheus:
          enabled: true 
        destinations: 
          - name: localProm
            type: prometheus
            url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
            metrics:
              enabled: true
        grafana:  
          enabled: true
          service:
            type: NodePort
            nodePort: 30001 



  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
