apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-dagger-workflow # Fixed name for ArgoCD
  generateName: example-dagger-workflow-
  namespace: argo
  annotations: {}
spec:
  entrypoint: workflow
  serviceAccountName: argo-workflow
  # Add volumes needed for the WorkflowTemplate
  volumes:
    - name: dagger-socket
      emptyDir: {}
    - name: dagger-storage
      emptyDir: {}
    - name: tmp-volume
      emptyDir: {}
  arguments:
    parameters:
      - name: repo
        value: "https://github.com/kpenfound/greetings-api.git"
  templates:
    - name: workflow
      dag:
        tasks:
          - name: dagger-test
            templateRef:
              name: dagger-template
              template: dagger-workflow-base
            arguments:
              parameters:
                - name: dagger-module
                  value: "github.com/kpenfound/dagger-modules/golang@v0.2.0"
                - name: dagger-function
                  value: "test --source=."
                - name: source-repo
                  value: "{{workflow.parameters.repo}}"
              artifacts:
                - name: project-source
                  git:
                    repo: "{{workflow.parameters.repo}}"
                    revision: "main"
                  path: /work
