# argocd namespace ──> brings the PEM from Key Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kv-github-pem
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: kv-github-pem
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: GITHUB-APP-PRIVATE-KEY
