apiVersion: v1
kind: ServiceAccount
metadata:
  name: acr-sa
  namespace: nextjs
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 6ac24c39-60c7-486d-a0ba-c52a6bca54a3
    azure.workload.identity/tenant-id: 0c4da9c5-40ea-4e7d-9c7a-e7308d4f8e38