apiVersion: v1
kind: ServiceAccount
metadata:
  name: acr-sa
  namespace: nextjs
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 5d6bf1a8-6398-4d2a-ac34-1e8c86d75ad5
    azure.workload.identity/tenant-id: 0c4da9c5-40ea-4e7d-9c7a-e7308d4f8e38