apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chat-env        # <-- becomes the k8s Secret name
  namespace: azure-chat # same namespace Radius deploys into
spec:
  secretStoreRef:
    name: azure-kv      # SecretStore created by your setup script
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: chat-env
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_URL        # key IN the k8s Secret
    remoteRef:
      key: POSTGRES-URL            # secret name IN Key Vault
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: OPENAI-API-KEY
  - secretKey: AZURE_API_KEY
    remoteRef:
      key: AZURE-API-KEY
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: ANTHROPIC-API-KEY
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: NEXTAUTH-SECRET
  - secretKey: NODE_ENV
    remoteRef:
      key: NODE-ENV
