apiVersion: v1
kind: ServiceAccount
metadata:
  name: acr-sa
  namespace: nextjs
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 7ac57bd8-11dc-4cb4-908b-a65dce1cd49e
    azure.workload.identity/tenant-id: 0c4da9c5-40ea-4e7d-9c7a-e7308d4f8e38