apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argo
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.41.9
    helm:
      releaseName: argo-workflows
      values: |
        controller:
          rbac:
            create: true

        server:
          enabled: true
          baseHref: /
          extraArgs:
            - "--auth-mode=server"
          secure: false

        singleNamespace: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
