apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-server-admin   # rename later; see ยง4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin       # broad, fine for local kind; swap later :contentReference[oaicite:2]{index=2}
subjects:
  - kind: ServiceAccount
    name: argo-server
    namespace: argo
