apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      serviceAccountName: argo-server            # <-- MUST match RBAC below
      containers:
        - name: argo-server
          image: argoproj/argocli:v3.6.5
          args:
            - server
            - --secure=false                    # plain HTTP inside cluster
            - --auth-mode=server                # hosted mode, fixes 401s :contentReference[oaicite:0]{index=0}
