apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default

  # where to install
  destination:
    name: in-cluster
    namespace: monitoring

  # what to install
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "8.*"       # current major
    helm:
      values: |
        service:
          type: NodePort
          nodePort: 30001
        adminPassword: "grafana"          # dev-only; store in secret for prod
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki-gateway.monitoring.svc.cluster.local
              - name: Tempo
                type: tempo
                url: http://tempo.monitoring.svc.cluster.local:3100
                traceToMetricsDatasource: Prometheus

  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
