apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "1.*"
    helm:
      values: |
        mode: standalone
        storage:
          type: filesystem
          filesystem:
            directory: /var/tempo

        traces:
          otlp:
            grpc:
              enabled: true
            http:
              enabled: true
          service:
            type: ClusterIP
            ports:
              - name: otlp-grpc
                port: 4317
              - name: otlp-http
                port: 4318
              - name: http
                port: 3100

        metricsGenerator:
          enabled: false
        tracesSampler:
          enabled: false

        # Disable distributed query components for standalone mode
        tempoQueryFrontend:
          enabled: false
        tempoQueryScheduler:
          enabled: false
        tempoQueryBackend:
          enabled: false

        test:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true