apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://qs-ygl2zollxkbc6.vault.azure.net
      serviceAccountRef:
        name: eso-azure-wi-sa
        namespace: external-secrets      # <— REQUIRED for ClusterSecretStore