apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chat-secrets
  namespace: azure-chat-chat        # <- MUST match the pod namespace
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: azure-keyvault-store      # <- ClusterSecretStore you already have
    kind: ClusterSecretStore
  target:
    name: chat-secrets              # name of the K8s Secret to create
    creationPolicy: Owner           # ESO owns & garbage‑collects it
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: OPENAI-API-KEY
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: POSTGRES-PASSWORD
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: ANTHROPIC-API-KEY
  - secretKey: AZURE_API_KEY
    remoteRef:
      key: AZURE-API-KEY
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: NEXTAUTH-SECRET
  - secretKey: NODE_ENV
    remoteRef:
      key: NODE-ENV
  - secretKey: POSTGRES_URL
    remoteRef:
      key: POSTGRES-URL
