apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chat-secrets
  namespace: azure 
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: chat-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI-API-KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRES-PASSWORD
